samples: "samples.tsv"
units: "units.tsv"

reference:
  fasta: ""
  loci: ""
  sites: ""
  intervals: ""
  adapter:
    fasta: ""
    fwd: "TACACTCTTTCCCTACACGACGCTCTTCCGATCT"
    rev: "GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT"

tools:
  common: "docker://marrip/common:1.1.0"
  cutadapt: "docker://marrip/cutadapt:3.0"
  fastqc: "docker://marrip/fastqc:0.11.9"
  gatk: "docker://broadinstitute/gatk:4.2.0.0"
  mosdepth: "docker://marrip/mosdepth:v0.3.1"
  ubuntu: "docker://ubuntu:18.04"
