samples: "samples.tsv"
units: "units.tsv"

reference:
  fasta: ""
  sites: ""
  adapter:
    fasta: ""
    fwd: "TACACTCTTTCCCTACACGACGCTCTTCCGATCT"
    rev: "GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT"

tools:
  bwa: "docker://marrip/bwa:0.7.15"
  cutadapt: "docker://marrip/cutadapt:3.3"
  fastqc: "docker://marrip/fastqc:0.11.9"
  python: "docker://python:3.9.1-slim-buster"
  trimmomatic: "docker://marrip/trimmomatic:0.39"
  ubuntu: "docker://ubuntu:18.04"
