samples: "samples.tsv"
units: "units.tsv"

reference:
  adapter:
    fwd: "TACACTCTTTCCCTACACGACGCTCTTCCGATCT"
    rev: "GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT"
  fasta: ""
  intervals: ""
  loci: ""
  sites: ""

tools:
  common: "docker://marrip/common:1.1.0"
  cutadapt: "docker://marrip/cutadapt:3.0"
  fastqc: "docker://marrip/fastqc:0.11.9"
  gatk: "docker://broadinstitute/gatk:4.2.0.0"
  mosdepth: "docker://marrip/mosdepth:v0.3.1"
  multiqc: "docker://marrip/multiqc:1.11"
  python: "docker://python:3.9.6-buster"
