$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  samples:
    type: string
  units:
    type: string
  reference:
    type: object
    properties:
      adapter:
        type: object
        properties:
          fwd:
            type: string
          rev:
            type: string
      fasta:
        type: string
      intervals:
        type: string
      loci:
        type: string
      sites:
        type: string
    required:
      - adapter
      - fasta
      - intervals
      - loci
      - sites
  tools:
    type: object
    properties:
      common:
        type: string
      cutadapt:
        type: string
      fastqc:
        type: string
      gatk:
        type: string
      mosdepth:
        type: string
  required:
    - samples
    - units
    - reference
    - tools
