samples: "samples.tsv"
units: "units.tsv"

reference:
  fasta: "reference/WASH7P.fna"
  loci: "reference/WASH7P.loci.txt"
  sites: "reference/known_indels.vcf"
  adapter:
    fasta: "reference/TruSeq3-PE.fa"
    fwd: "TACACTCTTTCCCTACACGACGCTCTTCCGATCT"
    rev: "GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT"

tools:
  bwa: "docker://marrip/bwa:0.7.15"
  common: "docker://marrip/common:1.0.0"
  cutadapt: "docker://marrip/cutadapt:3.3"
  fastqc: "docker://marrip/fastqc:0.11.9"
  mosdepth: "docker://marrip/mosdepth:v0.3.1"
  python: "docker://python:3.9.1-slim-buster"
  trimmomatic: "docker://marrip/trimmomatic:0.39"
  ubuntu: "docker://ubuntu:18.04"
